#FROM oraclelinux:8
# Using custom oraclelinux image with /dev removed
# This supports loading these containers using podman with
# an NFS backend
FROM hysds/jplsds-oraclelinux:8.10.250529-arm64

MAINTAINER Gerald Manipon (pymonger) "pymonger@gmail.com"
LABEL description "Base HySDS image"

# Set gosu version
ENV GOSU_VERSION 1.10

# Set docker-stats-on-exit-shim version
ENV DSOES_VERSION v1.0

# Set user and group
ENV USER root
ENV GROUP root

# get org and branch
ARG ORG
ARG BRANCH

# git url to hysds base puppet module
ENV GIT_URL https://github.com/${ORG}/puppet-hysds_base/raw/${BRANCH}/install.sh

# add latest repo version to invalidate cache
ADD https://api.github.com/repos/${ORG}/puppet-hysds_base/git/refs/heads/${BRANCH} version.json

# provision via puppet
RUN dnf install -y oracle-epel-release-el8 
RUN dnf install podman 
RUN dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo 
RUN dnf config-manager --set-disabled docker-ce-stable 
#RUN rpm --install --nodeps --replacefiles --excludepath=/usr/bin/runc https://download.docker.com/linux/centos/8/x86_64/stable/Packages/containerd.io-1.6.32-3.1.el8.x86_64.rpm 
RUN rpm --install --nodeps --replacefiles --excludepath=/usr/bin/runc https://download.docker.com/linux/centos/8/aarch64/stable/Packages/containerd.io-1.6.32-3.1.el8.aarch64.rpm 
RUN dnf install --enablerepo=docker-ce-stable docker-ce --nobest 
RUN dnf update -y 
RUN dnf install -y puppet wget curl git sudo 'dnf-command(config-manager)' which tar hostname 
RUN curl -skL ${GIT_URL} > /tmp/install.sh 
RUN chmod 755 /tmp/install.sh 
RUN /tmp/install.sh ${ORG} ${BRANCH} 
RUN rm -rf /etc/puppetlabs/code/modules/* /mnt/swapfile 
RUN dnf clean all 
RUN rm -f /tmp/install.sh 
RUN rm -rf /var/cache/dnf 
 # Commenting out for now as we are consistently getting
 # the following error: gpg: keyserver receive failed: Server indicated a failure
 # && for server in ha.pool.sks-keyservers.net \
 #     hkp://p80.pool.sks-keyservers.net:80 \
 #     keyserver.ubuntu.com \
 #     hkp://keyserver.ubuntu.com:80 \
 #     keyserver.pgp.com \
 #     pgp.mit.edu; do \
 #     gpg --keyserver "$server" --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 && break || : ; \
 #   done \
RUN curl -o /usr/local/bin/gosu -SL "https://github.com/hysds/gosu/releases/download/${GOSU_VERSION}/gosu-amd64" 
RUN curl -o /usr/local/bin/gosu.asc -SL "https://github.com/hysds/gosu/releases/download/${GOSU_VERSION}/gosu-amd64.asc" 
RUN gpg --verify /usr/local/bin/gosu.asc 
RUN rm /usr/local/bin/gosu.asc 
RUN rm -r /root/.gnupg/ 
RUN chmod +x /usr/local/bin/gosu 
RUN chmod u+s /usr/local/bin/gosu 
RUN curl -o /docker-stats-on-exit-shim -SL "https://github.com/hysds/docker-stats-on-exit-shim/releases/download/${DSOES_VERSION}/docker-stats-on-exit-shim" 
RUN chmod +x /docker-stats-on-exit-shim 
RUN chmod u+s /docker-stats-on-exit-shim 
RUN mkdir -p /${USER}/.local/share/containers 
RUN chown -R ${USER}:${GROUP} /${USER}

# Note VOLUME options must always happen after the chown call above
# RUN commands can not modify existing volumes
VOLUME /var/lib/containers
VOLUME /root/.local/share/containers

# Remove this directory as it contains extended attributes
RUN rm -rf /var/lib/containers/sigstore


# set default user and workdir
USER $USER
WORKDIR /$USER

# copy entrypoints
COPY docker/docker-entrypoint.sh /docker-entrypoint.sh
COPY docker/docker-entrypoint-with-stats.sh /docker-entrypoint-with-stats.sh

# set default entrypoint
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["/bin/bash", "--login"]
